let constants = {};

constants.DEFAULT_PROMPT_PRE = '<h2 style="text-align: center;"><span style="background-color: #ffff99;">Hey ',
constants.DEFAULT_PROMPT_POST = '!</span></h2>\r\n<h5 style="text-align: center;">My name\'s <span style="background-color: #00ffff;">Tiny the word processor</span> and I\'m your new best friend! Forget MS Word or Google Docs, because I am cooler than them.&nbsp;<img src="https://cloud.tinymce.com/stable/plugins/emoticons/img/smiley-cool.gif" alt="cool" /></h5>\r\n<h5 style="text-align: center;"><span style="color: #626262; background-color: #ffffff;"><span style="background-color: #ffcc99;">I promise to autosave your writing</span> so you can leave your work, even close this window etc and seamlessly resume when you are back!</span></h5>\r\n<h5 style="text-align: center;">Together we will <span style="background-color: #ccffcc;">write our way to the best universities in the world</span>!</h5>\r\n<h5 style="text-align: center;">You may <span style="background-color: #ff99cc;">begin your work by deleting all this text</span>.</h5>\r\n<p>&nbsp;</p>\r\n<p style="text-align: left;">&nbsp;</p>\r\n<h6 style="text-align: center;"><span style="font-family: century_gothic;"><strong><em>Quick tip:</em></strong></span></h6>\r\n<h5 style="text-align: center;"><span style="font-family: \'book antiqua\', palatino;">When you want to change font sizes, locate the menu bar where the \'File\', \'Edit\', \'View\', \'Insert\' options etc are found. </span></h5>\r\n<h5 style="text-align: center;"><span style="font-family: \'book antiqua\', palatino;">Click on the option BELOW the \'File\' option and choose from:</span></h5>\r\n<h1 style="text-align: center;"><span style="font-family: iskoola_pota;">Heading 1</span></h1>\r\n<h2 style="text-align: center;"><span style="font-family: iskoola_pota;">Heading 2</span></h2>\r\n<h3 style="text-align: center;"><span style="font-family: iskoola_pota;">Heading 3</span></h3>\r\n<h4 style="text-align: center;"><span style="font-family: iskoola_pota;">Heading 4</span></h4>\r\n<h5 style="text-align: center;"><span style="font-family: iskoola_pota;">Heading 5</span></h5>\r\n<h6 style="text-align: center;"><span style="font-family: iskoola_pota;">Heading 6</span></h6>\r\n<p style="text-align: center;"><span style="font-family: iskoola_pota;">Paragraph</span></p>';

constants.DAYS_FOR_INVITATION_CODE_TO_STAY_VALID  = 7;
constants.GARBAGE_COLLECT_IF_EXPIRED_FOR_NUM_DAYS = 7;
constants.LENGTH_OF_INVITATION_CODE = 10;

module.exports = constants;
